language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - $HOME/.m2

script:
- mvn install

sudo: false
git:
  depth: false

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull

before_script:
- _JAVA_OPTIONS=
