language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - $HOME/.m2

script:
- mvn clean install

sudo: false
git:
  depth: false

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull
- echo 'MAVEN_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=warn"' >~/.mavenrc
- mkdir -p $HOME/.downloads
- wget -N -q -O $HOME/.downloads/xswingx-0.2.zip 'https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/xswingx/xswingx-0.2.zip'
# The SHA256 checksum will break if the xswingx archive is updated.
- echo "048ca52ca279e53beef7c6a63036df5771d12dbc1ec223ec97569802e7055e52 $HOME/.downloads/xswingx-0.2.zip" | sha256sum -c
- mkdir -p $HOME/lib/jvm/jdesktop/jre/lib/xswingx
- unzip -o $HOME/.downloads/xswingx-0.2.zip -d $HOME/lib/jvm/jdesktop/jre/lib/xswingx

before_script:
- _JAVA_OPTIONS=
